name: Unit Tests
run-name: ${{ github.actor }} tests all the unit tests.

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  unitTests:
    name: Run units tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Execute Unit Test Command
        run: | 
          bash ./gradlew test
